package trianglio.rnd.lang.dot.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class AttributeList_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public AttributeList_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "trianglio.rnd.lang.dot.structure.AttributeList";
  }
}
