package trianglio.rnd.lang.dot.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class EdgeAttribute_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public EdgeAttribute_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "trianglio.rnd.lang.dot.structure.EdgeAttribute";
  }
}
