package trianglio.rnd.lang.dot.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class GraphAttribute_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public GraphAttribute_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "trianglio.rnd.lang.dot.structure.GraphAttribute";
  }
}
