package trianglio.rnd.lang.dot.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Dot_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("20a363b0-2d4e-4f48-8e60-37bc0b79373c(trianglio.rnd.lang.dot)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
