package trianglio.rnd.lang.dot.runtime;

/*Generated by MPS */

import java.util.Map;

public class AttributedObject {
  private Map<String, String> attributes;

  public void addAttribute(String key, String value) {
    attributes.put(key, value);
  }
}
