package trianglio.rnd.lang.dot.runtime;

/*Generated by MPS */

import java.util.Map;
import java.util.HashMap;
import java.util.List;

public class Graph extends AttributedObject {
  private Map<String, Node> nodes = new HashMap();
  private Map<Node, List<Edge>> edges = new HashMap();

  public void addNode(String nodeId, Node node) {
    nodes.put(nodeId, node);
  }

  public void addEdge(String sourceNodeId, String targetNodeId) {
  }

  public Node getNode(String nodeId) {
    return nodes.get(nodeId);
  }

  public List<Edge> getOutEdges(Node node) {
    return edges.get(node);
  }
}
