package trianglio.rnd.lang.dot.dfa.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Dfa_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("26f629dc-8cf8-42fd-a54e-2851bdb38b33(trianglio.rnd.lang.dot.dfa)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
