package trianglio.rnd.lang.dot.dfa.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class StateReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public StateReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "trianglio.rnd.lang.dot.dfa.structure.StateReference";
  }
}
