package trianglio.rnd.lang.dot.sandbox.sandbox;

/*Generated by MPS */

import trianglio.rnd.lang.dot.runtime.DumbDFA;
import trianglio.rnd.lang.dot.runtime.DFANoTransitionException;

public class test extends DumbDFA {
  public test() {
  }

  public int makeTransition(int currentState, char currentSymb) throws DFANoTransitionException {
    if (getState("0") == currentState && "hahaha".charAt(0) == currentSymb) {
      return getState("1");
    }
    if (getState("1") == currentState && "atata".charAt(0) == currentSymb) {
      return getState("2");
    }
    throw new DFANoTransitionException();
  }

  public void initNodes() {
    addState("0");
    if (false) {
      addAcceptanceState("0");
    }
    addState("1");
    if (false) {
      addAcceptanceState("1");
    }
    addState("2");
    if (false) {
      addAcceptanceState("2");
    }
  }

  public static void main(String[] args) {
    test dot = new test();
    System.out.println(dot.run(args[0]));
  }
}
